include: package:flutterando_analysis/flutter_package.yaml
linter:
  rules:
    prefer_single_quotes: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_print: true
    one_member_abstracts: true
    prefer_const_constructors: true