import 'package:flutter/material.dart';

TextTheme genTextTheme() {
  return const TextTheme(
    
    displayLarge: TextStyle(
        inherit: false,
        fontSize: 96,
        fontWeight: FontWeight.w300,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: -1.5,),
    displayMedium: TextStyle(
        inherit: false,
        fontSize: 60,
        fontWeight: FontWeight.w300,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: -0.5,),
    displaySmall: TextStyle(
        inherit: false,
        fontSize: 48,
        fontWeight: FontWeight.w400,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 0,),
    headlineLarge: TextStyle(
        inherit: false,
        fontSize: 40,
        fontWeight: FontWeight.w400,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 0.25,),
    headlineMedium: TextStyle(
        inherit: false,
        fontSize: 34,
        fontWeight: FontWeight.w400,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 0.25,),
    headlineSmall: TextStyle(
        inherit: false,
        fontSize: 24,
        fontWeight: FontWeight.w400,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 0,),
    titleLarge: TextStyle(
        inherit: false,
        fontSize: 20,
        fontWeight: FontWeight.w500,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 0.15,),
    titleMedium: TextStyle(
      //TODO change sizes title to 16> 18
        inherit: false,
        fontSize: 18,//16
        fontWeight: FontWeight.w400,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 0.15,),
    titleSmall: TextStyle(
        inherit: false,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 0.1,),
    bodyLarge: TextStyle(
        inherit: false,
        fontSize: 16,
        fontWeight: FontWeight.w400,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 0.5,),
    bodyMedium: TextStyle(
        inherit: false,
        fontSize: 14,
        fontWeight: FontWeight.w400,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 0.25,),
    bodySmall: TextStyle(
        inherit: false,
        fontSize: 12,
        fontWeight: FontWeight.w400,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 0.4,),
    labelLarge: TextStyle(
        inherit: false,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 1.25,),
    labelMedium: TextStyle(
        inherit: false,
        fontSize: 11,
        fontWeight: FontWeight.w400,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 1.5,),
    labelSmall: TextStyle(
        inherit: false,
        fontSize: 10,
        fontWeight: FontWeight.w400,
        textBaseline: TextBaseline.alphabetic,
        letterSpacing: 1.5,),
  );
}
