name: dependencies
description: Dependencies of this Project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+4
  shared_preferences: ^2.0.18
  flutterando_analysis: ^0.0.2
  dartz: ^0.10.1
  uuid: ^3.0.7
  d_chart: ^2.2.11
  intl: ^0.17.0
  drift: ^2.6.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

